### ISSUE TITLE
No possibility to define an error document

### ISSUE THREAD

**Issue by xavimb** [alexanderbird/s3-static-website-deploy#1]
When working with websites that use React and React Router, you need to set up your S3 bucket to redirect to `index.html` on error, so that it's React Router that takes care of handing the 404's.

Right now, every time I deploy something using this plugin (which btw, it's been super useful and easy to set up!), I have to set the error document manually in order to make it work properly.

It would be very useful to have an option to set the error document.

**Comment by alexanderbird** [comment]
Could you try out that branch I created and let me know if it works?

**Comment by alexanderbird** [comment]
Happy to help! Glad you find it useful.

**Comment by xavimb** [comment]
Are you planning to publish a new version to npm?

**Comment by alexanderbird** [comment]
Ah yes -- just did that now
